### ISSUE TITLE
SDM230 over RTU data decode does not work?

### ISSUE THREAD

**Issue by klaushasselbach** [nmakel/sdm_modbus#25]
>>> device=sdm_modbus.sdm.SDM230(device="/dev/serial0",baud=9600, parity="N", stopbits=1,timeout=2)
>>> data =device.read_all(sdm_modbus.registerType.INPUT)
>>> data
{'total_demand_current': 1.7340985536575317, 'maximum_total_demand_current': 14.856954574584961, 'total_energy_active': 124.87000274658203, 'total_energy_reactive': 61.827999114990234}
>>> device.read_input("current")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'SDM230' object has no attribute 'read_input'
>>> device
SDM230(/dev/serial0, connectionType.RTU: stopbits=1, parity=N, baud=9600, timeout=2, retries=3, unit=0x1)
>>> device.read("voltage")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/sdm_modbus/meter.py", line 303, in read
    return self._read(self.registers[key])
  File "/home/pi/sdm_modbus/meter.py", line 216, in _read
    return self._decode_value(self._read_input_registers(address, length), length, dtype, vtype)
  File "/home/pi/sdm_modbus/meter.py", line 199, in _decode_value
    return vtype(data.decode_32bit_float())
AttributeError: 'NoneType' object has no attribute 'decode_32bit_float'

**Comment by klaushasselbach** [comment]
here we are
(6, 2, <registerType.INPUT: 1>, <registerDataType.FLOAT32: 11>, <class 'float'>, 'Current', 'A', 1, 1)
(0, 2, <registerType.INPUT: 1>, <registerDataType.FLOAT32: 11>, <class 'float'>, 'Voltage', 'V', 1, 1)
Traceback (most recent call last):
  File "/home/pi/main_sdm_modbus.py", line 58, in <module>
  File "/home/pi/main_sdm_modbus.py", line 50, in main
AttributeError: 'SDM230' object has no attribute 'read_input'
