### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode_32bit_float'

### ISSUE THREAD

**Issue by Maikel-K** [nmakel/sdm_modbus#4]
Hi Niels,

Happy newyear!

I got an issue with reading a SDM120 via ModbusTCP
Following script causes this an error as described below:
#!/usr/bin/env python3

import argparse
import json
import sdm_modbus
import time
from datetime import date
import urllib

if __name__ == "__main__":
    argparser = argparse.ArgumentParser()
    argparser.add_argument("host", type=str, help="ModbusTCP address")
    argparser.add_argument("port", type=int, help="ModbusTCP port")
    argparser.add_argument("--timeout", type=int, default=1, help="Connection timeout")
    argparser.add_argument("--unit", type=int, default=1, help="Modbus unit")
    argparser.add_argument("--json", action="store_true", default=False, help="Output as JSON")
    args = argparser.parse_args()

    meter = sdm_modbus.SDM120(
        host=args.host,
        port=args.port,
        timeout=args.timeout,
        unit=args.unit
    )

    if args.json:
        print(json.dumps(meter.read_all(), indent=4))
    else:
        print(f"{meter}:")
        print("\nInput Registers:")
        print(meter.read("voltage"))

 python3 test120.py 192.168.1.115 8899
SDM120(192.168.1.115:8899, connectionType.TCP: timeout=1, retries=3, unit=0x1):

Input Registers:
Traceback (most recent call last):
  File "test120.py", line 31, in <module>
    print(meter.read("voltage"))
  File "/home/pi/sdmmodbus/sdm_modbus/__init__.py", line 233, in read
    return self._read(self.registers[key])
  File "/home/pi/sdmmodbus/sdm_modbus/__init__.py", line 153, in _read
    return self._decode_value(self._read_input_registers(address, length), length, dtype, vtype)
  File "/home/pi/sdmmodbus/sdm_modbus/__init__.py", line 142, in _decode_value
    return vtype(data.decode_32bit_float())
AttributeError: 'NoneType' object has no attribute 'decode_32bit_float'

**Comment by Maikel-K** [comment]
Nevermind... somehow the Modbus setting was turned of in my EE11.....
